import { assetUrl } from './assetUrl.js';

/** Shared NPC animation clips (standard pudgy skeleton). */
export const NPC_ANIMS = {
  idle1: assetUrl('/assets/models/animations/NPC_Animations/Anim_Idle_01_02.fbx'),
  idle2: assetUrl('/assets/models/animations/NPC_Animations/Anim_Idle_02_02.fbx'),
  idle3: assetUrl('/assets/models/animations/NPC_Animations/Anim_Idle_03_02.fbx'),
  idle4: assetUrl('/assets/models/animations/NPC_Animations/Anim_Idle_04_02.fbx'),
  wave: assetUrl('/assets/models/animations/NPC_Animations/Anim_Wave_02.fbx'),
  talk: assetUrl('/assets/models/animations/NPC_Animations/Anim_NPC_Talk_02.fbx'),
  talkHappy: assetUrl('/assets/models/animations/NPC_Animations/Anim_NPC_TalkHappy_02.fbx'),
  talkConfused: assetUrl('/assets/models/animations/NPC_Animations/Anim_NPC_TalkConfused_02.fbx'),
  walk1: assetUrl('/assets/models/animations/NPC_Animations/Anim_NPC_WalkStyle_01_02.fbx'),
  walk2: assetUrl('/assets/models/animations/NPC_Animations/Anim_NPC_WalkStyle_02_02.fbx'),
  bonkoIdle: assetUrl('/assets/models/animations/NPC_Animations/Anim_BonkoIdle_01.fbx'),
  bonkoTalk: assetUrl('/assets/models/animations/NPC_Animations/Anim_BonkoTalk_01.fbx'),
};

/** All NPC character models under public/assets/models/npcs/. */
export const NPC_MODELS = {
  adam: assetUrl('/assets/models/npcs/NPC_Adam.fbx'),
  alexSvenavik: assetUrl('/assets/models/npcs/NPC_AlexSvenavik.fbx'),
  archer: assetUrl('/assets/models/npcs/NPC_Archer.fbx'),
  arcticAnnie: assetUrl('/assets/models/npcs/NPC_ArcticAnnie.fbx'),
  bailey: assetUrl('/assets/models/npcs/NPC_Bailey.fbx'),
  bean: assetUrl('/assets/models/npcs/NPC_Bean.fbx'),
  bellaBucket: assetUrl('/assets/models/npcs/NPC_BellaBucket.fbx'),
  bogfather: assetUrl('/assets/models/npcs/NPC_Bogfather.fbx'),
  bonko: assetUrl('/assets/models/npcs/NPC_Bonko.fbx'),
  bowlcut: assetUrl('/assets/models/npcs/NPC_Bowlcut_Var1.fbx'),
  bowlcutVar2: assetUrl('/assets/models/npcs/NPC_Bowlcut_Var2.fbx'),
  bowlcutVar3: assetUrl('/assets/models/npcs/NPC_Bowlcut_Var3.fbx'),
  bowlcutVar4: assetUrl('/assets/models/npcs/NPC_Bowlcut_Var4.fbx'),
  bowlcutVar5: assetUrl('/assets/models/npcs/NPC_Bowlcut_Var5.fbx'),
  breezy: assetUrl('/assets/models/npcs/NPC_BreezyBeakBenny.fbx'),
  brighty: assetUrl('/assets/models/npcs/NPC_Brighty.fbx'),
  bryanPellagrino: assetUrl('/assets/models/npcs/NPC_BryanPellagrino.fbx'),
  burnasso: assetUrl('/assets/models/npcs/NPC_Burnasso.fbx'),
  carlyCognito: assetUrl('/assets/models/npcs/NPC_CarlyCognito.fbx'),
  chanceChickHead: assetUrl('/assets/models/npcs/NPC_ChanceChickHead.fbx'),
  child: assetUrl('/assets/models/npcs/NPC_Child.fbx'),
  churro: assetUrl('/assets/models/npcs/NPC_Churro.fbx'),
  coco: assetUrl('/assets/models/npcs/NPC_Coco.fbx'),
  daoJones: assetUrl('/assets/models/npcs/NPC_DaoJones.fbx'),
  dapperSnap: assetUrl('/assets/models/npcs/NPC_DapperSnap.fbx'),
  darrenSRS: assetUrl('/assets/models/npcs/NPC_DarrenSRS.fbx'),
  defiSushi: assetUrl('/assets/models/npcs/NPC_DefiSushi.fbx'),
  disco: assetUrl('/assets/models/npcs/NPC_Disco.fbx'),
  dunc: assetUrl('/assets/models/npcs/NPC_Dunc.fbx'),
  egg: assetUrl('/assets/models/npcs/NPC_Egg.fbx'),
  elizabeth: assetUrl('/assets/models/npcs/NPC_Elizabeth.fbx'),
  elizabeth01: assetUrl('/assets/models/npcs/NPC_Elizabeth_01.fbx'),
  elizabeth03: assetUrl('/assets/models/npcs/NPC_Elizabeth_03.fbx'),
  evie: assetUrl('/assets/models/npcs/NPC_Evie.fbx'),
  finch: assetUrl('/assets/models/npcs/NPC_Finch.fbx'),
  fisherpengRandy: assetUrl('/assets/models/npcs/NPC_FisherpengRandy.fbx'),
  froggy: assetUrl('/assets/models/npcs/NPC_Froggy.fbx'),
  goldenEggGabe: assetUrl('/assets/models/npcs/NPC_GoldenEggGabe.fbx'),
  goose: assetUrl('/assets/models/npcs/NPC_Goose.fbx'),
  gretz: assetUrl('/assets/models/npcs/NPC_Gretz.fbx'),
  hanzo: assetUrl('/assets/models/npcs/NPC_Hanzo.fbx'),
  hugo: assetUrl('/assets/models/npcs/NPC_Hugo.fbx'),
  husker: assetUrl('/assets/models/npcs/NPC_Husker.fbx'),
  kache: assetUrl('/assets/models/npcs/NPC_Kache.fbx'),
  kingDiminimus: assetUrl('/assets/models/npcs/NPC_KingDiminimus.fbx'),
  leawin: assetUrl('/assets/models/npcs/NPC_Leawin.fbx'),
  lightning: assetUrl('/assets/models/npcs/NPC_Lightning.fbx'),
  manoMohawk: assetUrl('/assets/models/npcs/NPC_ManoMohawk.fbx'),
  marth10: assetUrl('/assets/models/npcs/NPC_Marth10.fbx'),
  mase: assetUrl('/assets/models/npcs/NPC_Mase.fbx'),
  medx: assetUrl('/assets/models/npcs/NPC_MEDX.fbx'),
  mungo: assetUrl('/assets/models/npcs/NPC_Mungo.fbx'),
  numberOnePengu: assetUrl('/assets/models/npcs/NPC_NumberOnePengu.fbx'),
  ori: assetUrl('/assets/models/npcs/NPC_Ori.fbx'),
  pancakes: assetUrl('/assets/models/npcs/NPC_Pancakes.fbx'),
  pengu: assetUrl('/assets/models/npcs/NPC_PENGU.fbx'),
  penguinCurator: assetUrl('/assets/models/npcs/NPC_PenguinCurator.fbx'),
  polly: assetUrl('/assets/models/npcs/NPC_Polly.fbx'),
  puddles: assetUrl('/assets/models/npcs/NPC_Puddles.fbx'),
  pudginoBeverlyChills: assetUrl('/assets/models/npcs/NPC_Pudgino_BeverlyChills.fbx'),
  pudginoBlubberBay: assetUrl('/assets/models/npcs/NPC_Pudgino_BlubberBay.fbx'),
  pudginoBoogieBerg: assetUrl('/assets/models/npcs/NPC_Pudgino_BoogieBerg.fbx'),
  pudginoBowlcutBeach: assetUrl('/assets/models/npcs/NPC_Pudgino_BowlcutBeach.fbx'),
  pudginoPudgyPort: assetUrl('/assets/models/npcs/NPC_Pudgino_PudgyPort.fbx'),
  pudginoRegular: assetUrl('/assets/models/npcs/NPC_Pudgino_Regular.fbx'),
  q: assetUrl('/assets/models/npcs/NPC_Q.fbx'),
  rooney: assetUrl('/assets/models/npcs/NPC_Rooney.fbx'),
  sauceror: assetUrl('/assets/models/npcs/NPC_Sauceror.fbx'),
  scoops: assetUrl('/assets/models/npcs/NPC_Scoops.fbx'),
  sgtSurferdude: assetUrl('/assets/models/npcs/NPC_SgtSurferdude.fbx'),
  swankyHank: assetUrl('/assets/models/npcs/NPC_SwankyHank.fbx'),
  tiny: assetUrl('/assets/models/npcs/NPC_Tiny.fbx'),
  tofu: assetUrl('/assets/models/npcs/NPC_Tofu.fbx'),
  toots: assetUrl('/assets/models/npcs/NPC_Toots.fbx'),
};

/**
 * @typedef {{
 *   id: string,
 *   model: keyof typeof NPC_MODELS,
 *   skeleton?: 'standard',
 *   clips: string[],
 *   position: {x:number,y:number,z:number},
 *   yawDeg?: number,
 *   wanderRadius?: number,
 * }} NpcPlacement
 */

/** NPCs for standalone Individual islands / Pengu Plaza.
 * position.x/z are offsets from the island AABB center (not world origin).
 * Include a walk* clip to enable wander locomotion.
 */
export const INDIVIDUAL_NPCS = [
  {
    id: 'breezy',
    model: 'breezy',
    skeleton: 'standard',
    clips: ['walk1', 'wave', 'idle1', 'talk'],
    position: { x: 2.5, y: 0, z: 2 },
    yawDeg: 210,
    wanderRadius: 5,
  },
  {
    id: 'evie',
    model: 'evie',
    skeleton: 'standard',
    clips: ['walk2', 'talkHappy', 'idle3', 'wave'],
    position: { x: -2.5, y: 0, z: 1.5 },
    yawDeg: 140,
    wanderRadius: 5,
  },
  {
    id: 'bowlcut',
    model: 'bowlcut',
    skeleton: 'standard',
    clips: ['walk1', 'idle2', 'talk'],
    position: { x: 1.5, y: 0, z: -2.5 },
    yawDeg: 20,
    wanderRadius: 5,
  },
];

/** Sorted model keys for scene-dropdown NPC previews. */
export const NPC_MODEL_KEYS = Object.keys(NPC_MODELS);

