#!/usr/bin/env node
/**
 * Sync cosmetic trait FBXs from Unity exports → public/assets/models/player/traits/
 * and regenerate src/config/traitsCatalog.generated.js
 *
 * Usage: node scripts/syncTraitsFromUnity.mjs
 */
import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'fs';
import { basename, join, relative } from 'path';

const ROOT = new URL('..', import.meta.url).pathname;
const DEFS_DIR = join(
  ROOT,
  'Assets/Scriptable Objects/Definitions/Trait Definitions/Player Trait Definitions',
);
const EXPORT_ROOTS = [
  join(ROOT, 'Assets/PudgyWorldAssets/Pudgy Models/Pudgy Models/PlayerPudgys_V2/01_PlayerTraits/Exports'),
  join(ROOT, 'Assets/PudgyWorldAssets/Pudgy Models/PlayerPudgys_V2/01_PlayerTraits/Exports'),
  join(ROOT, 'Assets/PudgyWorldAssets/Pudgy Models/PlayerPudgys/01_Player_Traits/Exports'),
];
const OUT_DIR = join(ROOT, 'public/assets/models/player/traits');
const OUT_CATALOG = join(ROOT, 'src/config/traitsCatalog.generated.js');

const TYPE_MAP = {
  0: 'skin',
  1: 'head',
  2: 'face',
  3: 'body',
  4: 'fullBody',
};

const RARITIES = new Set(['common', 'uncommon', 'rare', 'epic', 'mythical', 'default']);

function parseTraitAsset(path) {
  const text = readFileSync(path, 'utf8');
  const id = text.match(/_id: (\S+)/)?.[1];
  const displayName = text.match(/_displayName: (.+)/)?.[1]?.trim();
  const typeNum = Number(text.match(/_type: (\d+)/)?.[1]);
  const type = TYPE_MAP[typeNum];
  if (!id || !type) return null;
  return { id, type, displayName };
}

function labelFromTrait({ id, displayName }) {
  if (displayName && displayName !== id) {
    return displayName.replace(/([a-z])([A-Z])/g, '$1 $2');
  }
  const parts = id.split('_').slice(1);
  if (parts.length && RARITIES.has(parts[parts.length - 1])) parts.pop();
  return parts.map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join(' ');
}

function buildFbxIndex() {
  /** @type {Map<string, string>} */
  const index = new Map();
  for (const root of EXPORT_ROOTS) {
    if (!existsSync(root)) continue;
    for (const name of readdirSafe(root)) {
      if (!name.toLowerCase().endsWith('.fbx')) continue;
      const full = join(root, name);
      const key = basename(name, '.fbx').toLowerCase().replace(/_/g, '');
      if (!index.has(key)) index.set(key, full);
    }
  }
  return index;
}

function readdirSafe(dir) {
  try {
    return readdirSync(dir);
  } catch {
    return [];
  }
}

function findFbx(id, index) {
  const parts = id.split('_');
  const prefix = parts[0].charAt(0).toUpperCase() + parts[0].slice(1);
  const pascalRest = parts.slice(1).map((p) => p.charAt(0).toUpperCase() + p.slice(1)).join('');
  const keys = [
    id.replace(/_/g, '').toLowerCase(),
    (prefix + pascalRest).toLowerCase(),
  ];
  for (const key of keys) {
    const hit = index.get(key);
    if (hit) return hit;
  }
  const base = parts.slice(0, -1).join('').toLowerCase();
  if (RARITIES.has(parts[parts.length - 1])) {
    for (const [key, path] of index) {
      if (key.startsWith(base)) return path;
    }
  }
  return null;
}

function shouldCopy(src, dest) {
  if (!existsSync(dest)) return true;
  return statSync(src).mtimeMs > statSync(dest).mtimeMs;
}

function main() {
  mkdirSync(OUT_DIR, { recursive: true });
  const fbxIndex = buildFbxIndex();
  const traits = [];

  for (const name of readdirSafe(DEFS_DIR)) {
    if (!name.endsWith('.asset')) continue;
    const def = parseTraitAsset(join(DEFS_DIR, name));
    if (!def) continue;
    const src = findFbx(def.id, fbxIndex);
    if (!src) {
      console.warn('[sync] no FBX for', def.id);
      continue;
    }
    const dest = join(OUT_DIR, `${def.id}.fbx`);
    if (shouldCopy(src, dest)) {
      cpSync(src, dest);
      console.log('copied', relative(ROOT, dest));
    }
    traits.push({
      id: def.id,
      type: def.type,
      label: labelFromTrait(def),
      fbx: `/assets/models/player/traits/${def.id}.fbx`,
    });
  }

  traits.sort((a, b) => {
    const typeOrder = { skin: 0, head: 1, face: 2, body: 3 };
    const td = (typeOrder[a.type] ?? 9) - (typeOrder[b.type] ?? 9);
    if (td !== 0) return td;
    return a.label.localeCompare(b.label);
  });

  const body = traits
    .map(
      (t) =>
        `  { id: '${t.id}', type: '${t.type}', label: '${escapeJs(t.label)}', fbx: assetUrl('${t.fbx}') },`,
    )
    .join('\n');

  writeFileSync(
    OUT_CATALOG,
    `/** Auto-generated by scripts/syncTraitsFromUnity.mjs — do not edit by hand. */\nimport { assetUrl } from './assetUrl.js';\n\nexport const GENERATED_TRAIT_CATALOG = [\n${body}\n];\n`,
  );

  console.log(`\nSynced ${traits.length} traits → ${relative(ROOT, OUT_DIR)}`);
  console.log(`Catalog → ${relative(ROOT, OUT_CATALOG)}`);
}

function escapeJs(s) {
  return s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

main();
