#!/usr/bin/env node
/**
 * Sync fish FBXs from Unity → public/assets/models/fish/
 * and regenerate src/config/fishCatalog.generated.js
 *
 * Usage: node scripts/syncFishFromUnity.mjs
 */
import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  writeFileSync,
} from 'fs';
import { join, relative } from 'path';

const ROOT = new URL('..', import.meta.url).pathname;
const DEFS_DIR = join(
  ROOT,
  'Assets/Scriptable Objects/Definitions/Fish Definitions',
);
const MODELS_DIR = join(ROOT, 'Assets/PudgyWorldAssets/Fish Models');
const OUT_DIR = join(ROOT, 'public/assets/models/fish');
const OUT_CATALOG = join(ROOT, 'src/config/fishCatalog.generated.js');

function labelFromId(id) {
  const raw = id.replace(/^fish\./, '');
  return raw
    .split('_')
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join(' ');
}

function sourceFbxForIndex(index) {
  if (index < 0) return join(MODELS_DIR, 'Fish_SharkSuit.fbx');
  return join(MODELS_DIR, `${index}.fbx`);
}

function destNameForIndex(index) {
  if (index < 0) return 'Fish_SharkSuit.fbx';
  return `${index}.fbx`;
}

function main() {
  mkdirSync(OUT_DIR, { recursive: true });
  const fish = [];

  for (const name of readdirSync(DEFS_DIR)) {
    if (!name.endsWith('.asset')) continue;
    const text = readFileSync(join(DEFS_DIR, name), 'utf8');
    const id = text.match(/_id: (\S+)/)?.[1];
    const index = Number(text.match(/_index: (-?\d+)/)?.[1]);
    if (!id || Number.isNaN(index)) continue;

    const src = sourceFbxForIndex(index);
    if (!existsSync(src)) {
      console.warn('[sync:fish] missing FBX for', id, index);
      continue;
    }
    const destFile = destNameForIndex(index);
    const dest = join(OUT_DIR, destFile);
    cpSync(src, dest);
    fish.push({
      id,
      index,
      label: labelFromId(id),
      fbx: `/assets/models/fish/${destFile}`,
    });
  }

  fish.sort((a, b) => a.label.localeCompare(b.label));

  const body = fish
    .map(
      (f) =>
        `  { id: '${f.id}', index: ${f.index}, label: '${f.label.replace(/'/g, "\\'")}', fbx: assetUrl('${f.fbx}') },`,
    )
    .join('\n');

  writeFileSync(
    OUT_CATALOG,
    `/** Auto-generated by scripts/syncFishFromUnity.mjs — do not edit by hand. */\nimport { assetUrl } from './assetUrl.js';\n\nexport const GENERATED_FISH_CATALOG = [\n${body}\n];\n`,
  );

  console.log(`Synced ${fish.length} fish → ${relative(ROOT, OUT_DIR)}`);
  console.log(`Catalog → ${relative(ROOT, OUT_CATALOG)}`);
}

main();
